version: '3.9'

services:

  app:
    build: .
    container_name: easy_turnos_app
    restart: always
    env_file: .env
    ports:
      - "3001:3001"
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/node_modules
      - ./prisma:/app/prisma
    environment:
      DATABASE_URL: ${DATABASE_URL}
      JWT_SECRET: ${JWT_SECRET}
      PORT: ${PORT}
      DIABCORE_FRONTEND_URL: ${DIABCORE_FRONTEND_URL}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}

  db:
    image: postgres
    restart: always
    hostname: postgres
    container_name: easy_turnos_db
    shm_size: 128mb
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
